const reviewdata = [
  {
    id: "1",
    Name: "Wilson Radadia",
    Gender: "male",
    Age: "20",
    Consulting_date: "26-06-21",
    Disease: "Chicken-Pox",
    Review_date: "27-06-2021",
    Tocken_No: "CjP07",
    Review_star: "4",
    Review_text:
      "The management is awesome and I am glad that online service is also available that makes easier for the patients to book the appointment",
  },
  {
    id: "2",
    Name: "Wilson Radadia",
    Gender: "male",
    Age: "20",
    Consulting_date: "26-06-21",
    Disease: "Chicken-Pox",
    Review_date: "27-06-2021",
    Tocken_No: "CjP07",
    Review_star: "4",
    Review_text:
      "The management is awesome and I am glad that online service is also available that makes easier for the patients to book the appointment",
  },
  {
    id: "3",
    Name: "Wilson Radadia",
    Gender: "male",
    Age: "20",
    Consulting_date: "26-06-21",
    Disease: "Chicken-Pox",
    Review_date: "27-06-2021",
    Tocken_No: "CjP07",
    Review_star: "4",
    Review_text:
      "The management is awesome and I am glad that online service is also available that makes easier for the patients to book the appointment",
  },
  {
    id: "4",
    Name: "Wilson Radadia",
    Gender: "male",
    Age: "20",
    Consulting_date: "26-06-21",
    Disease: "Chicken-Pox",
    Review_date: "27-06-2021",
    Tocken_No: "CjP07",
    Review_star: "4",
    Review_text:
      "The management is awesome and I am glad that online service is also available that makes easier for the patients to book the appointment",
  },
  {
    id: "5",
    Name: "Wilson Radadia",
    Gender: "male",
    Age: "20",
    Consulting_date: "26-06-21",
    Disease: "Chicken-Pox",
    Review_date: "27-06-2021",
    Tocken_No: "CjP07",
    Review_star: "4",
    Review_text:
      "The management is awesome and I am glad that online service is also available that makes easier for the patients to book the appointment",
  },
  {
    id: "6",
    Name: "Wilson Radadia",
    Gender: "male",
    Age: "20",
    Consulting_date: "26-06-21",
    Disease: "Chicken-Pox",
    Review_date: "27-06-2021",
    Tocken_No: "CjP07",
    Review_star: "4",
    Review_text:
      "The management is awesome and I am glad that online service is also available that makes easier for the patients to book the appointment",
  },
  {
    id: "7",
    Name: "Wilson Radadia",
    Gender: "male",
    Age: "20",
    Consulting_date: "26-06-21",
    Disease: "Chicken-Pox",
    Review_date: "27-06-2021",
    Tocken_No: "CjP07",
    Review_star: "4",
    Review_text:
      "The management is awesome and I am glad that online service is also available that makes easier for the patients to book the appointment",
  },
  {
    id: "8",
    Name: "Wilson Radadia",
    Gender: "male",
    Age: "20",
    Consulting_date: "26-06-21",
    Disease: "Chicken-Pox",
    Review_date: "27-06-2021",
    Tocken_No: "CjP07",
    Review_star: "4",
    Review_text:
      "The management is awesome and I am glad that online service is also available that makes easier for the patients to book the appointment",
  },
  {
    id: "9",
    Name: "Wilson Radadia",
    Gender: "male",
    Age: "20",
    Consulting_date: "26-06-21",
    Disease: "Chicken-Pox",
    Review_date: "27-06-2021",
    Tocken_No: "CjP07",
    Review_star: "4",
    Review_text:
      "The management is awesome and I am glad that online service is also available that makes easier for the patients to book the appointment",
  },
  {
    id: "10",
    Name: "Wilson Radadia",
    Gender: "male",
    Age: "20",
    Consulting_date: "26-06-21",
    Disease: "Chicken-Pox",
    Review_date: "27-06-2021",
    Tocken_No: "CjP07",
    Review_star: "4",
    Review_text:
      "The management is awesome and I am glad that online service is also available that makes easier for the patients to book the appointment",
  },
];

export default reviewdata;
