var notificationData = [
  {
    id: "1",
    Title: "Trimurti Hospital",
    HospitalCategory: "Multispecialists Hospital",
    Location: "Zanzarda Road",
    Address:
      "TRIMURTI Hospital, ABC Block, XYZ society, MNOCity,Pin Code:362001",
    Email: "abc@gmail.com",
    Phone: "9990012345",
    Link: "https://goo.gl/maps/4qWgu6CGpDZ1274X8",
    Ratingscount: "(15092)",
    Doctors: "25",
    Ratings: "4",
  },

  {
    id: "2",
    Title: "MotherHood Hospital",
    HospitalCategory: "Cancer Hospital",
    Location: "VigyanNagar",
    Address:
      "TRIMURTI Hospital, ABC Block, XYZ society, MNOCity,Pin Code:362001",
    Email: "abc@gmail.com",
    Phone: "9990012345",
    Link: "https://goo.gl/maps/4qWgu6CGpDZ1274X8",
    Ratingscount: "(5097)",
    Doctors: "20",
    Ratings: "4",
  },
  {
    id: "3",
    Title: "Sparsh Hospital",
    HospitalCategory: "Cardio Hospital",
    Location: "Indira Nagar",
    Address:
      "TRIMURTI Hospital, ABC Block, XYZ society, MNOCity,Pin Code:362001",
    Email: "abc@gmail.com",
    Phone: "9990012345",
    Link: "https://goo.gl/maps/4qWgu6CGpDZ1274X8",
    Ratingscount: "(7092)",
    Doctors: "35",
    Ratings: "5",
  },
  {
    id: "4",
    Title: "Care and Cure Hospital",
    HospitalCategory: "Multispecialists Hospital",
    Location: "Indraprasth",
    Address:
      "TRIMURTI Hospital, ABC Block, XYZ society, MNOCity,Pin Code:362001",
    Email: "abc@gmail.com",
    Phone: "9990012345",
    Link: "https://goo.gl/maps/4qWgu6CGpDZ1274X8",
    Ratingscount: "(292)",
    Doctors: "25",
    Ratings: "3",
  },
  {
    id: "5",
    Title: "Trimurti Hospital 2",
    HospitalCategory: "Cancer Hospital",
    Location: "Indira Gandhi Chowk",
    Address:
      "TRIMURTI Hospital, ABC Block, XYZ society, MNOCity,Pin Code:362001",
    Email: "abc@gmail.com",
    Phone: "9990012345",
    Link: "https://goo.gl/maps/4qWgu6CGpDZ1274X8",
    Ratingscount: "(15092)",
    Doctors: "15",
    Ratings: "4",
  },
  {
    id: "6",
    Title: "Trimurti Hospital 3",
    HospitalCategory: "NeuroSpecialists Hospital",
    Location: "Manek Chowk",
    Address:
      "TRIMURTI Hospital, ABC Block, XYZ society, MNOCity,Pin Code:362001",
    Email: "abc@gmail.com",
    Phone: "9990012345",
    Link: "https://goo.gl/maps/4qWgu6CGpDZ1274X8",
    Ratingscount: "(993)",
    Doctors: "25",
    Ratings: "5",
  },
  {
    id: "7",
    Title: "Trimurti Hospital 4",
    HospitalCategory: "Cardio Hospital",
    Location: "SG Highway",
    Address:
      "TRIMURTI Hospital, ABC Block, XYZ society, MNOCity,Pin Code:362001",
    Email: "abc@gmail.com",
    Phone: "9990012345",
    Link: "https://goo.gl/maps/4qWgu6CGpDZ1274X8",
    Ratingscount: "(8032)",
    Doctors: "51",
    Ratings: "2",
  },
  {
    id: "8",
    Title: "MotherHood Hospital 2 ",
    HospitalCategory: "Multispecialists Hospital",
    Location: "Kalwa Chowk",
    Address:
      "TRIMURTI Hospital, ABC Block, XYZ society, MNOCity,Pin Code:362001",
    Email: "abc@gmail.com",
    Phone: "9990012345",
    Link: "https://goo.gl/maps/4qWgu6CGpDZ1274X8",
    Ratingscount: "(6092)",
    Doctors: "31",
    Ratings: "3",
  },
  {
    id: "9",
    Title: "MotherMary Hospital",
    HospitalCategory: "NeuroSpecialists Hospital",
    Location: "NehruNagar",
    Address:
      "TRIMURTI Hospital, ABC Block, XYZ society, MNOCity,Pin Code:362001",
    Email: "abc@gmail.com",
    Phone: "9990012345",
    Link: "https://goo.gl/maps/4qWgu6CGpDZ1274X8",
    Ratingscount: "(1092)",
    Doctors: "47",
    Ratings: "4",
  },
  {
    id: "10",
    Title: "MotherLand Hospital",
    HospitalCategory: "Cancer Hospital",
    Location: "SwaastiJain Nagar",
    Address:
      "TRIMURTI Hospital, ABC Block, XYZ society, MNOCity,Pin Code:362001",
    Email: "abc@gmail.com",
    Phone: "9990012345",
    Link: "https://goo.gl/maps/4qWgu6CGpDZ1274X8",
    Ratingscount: "(9092)",
    Doctors: "68",
    Ratings: "5",
  },
];

export default notificationData;
