var flatlistdata = [
  {
    id: "1",
    Name: "Dr. Niraj Mehra",
    Category: "MD",
    Hospital: "Trimurti Hospital",
    Time: "9:00 am-8:00pm",
    TotalConsultation: "2980",
    Ratingscount: "500+",
    Ratings: "4 Star Reviews",
    Fee: "2000",
    uri: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: "2",
    Name: "Dr. Hansraj Hathi",
    Category: "Gynecologist",
    Hospital: "Appolo Hospital",
    Time: "12:00 pm-8:00pm",
    TotalConsultation: "5010",
    Ratingscount: "800+",
    Ratings: "4 Star Reviews",
    Fee: "2500",
    uri: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: "3",
    Name: "Dr. Venkat Maliya",
    Category: "Cardiologist",
    Hospital: "Jivraj Mehta Hospital",
    Time: "10:00 am-10:00pm",
    TotalConsultation: "2080",
    Ratingscount: "300+",
    Ratings: "4 Star Reviews",
    Fee: "1000",
    uri: "https://picsum.photos/200/300?grayscale",
  },
  {
    id: "4",
    Name: "Dr. Chelsi Desoza",
    Category: "Orthodontist",
    Hospital: "Javiya Hospital",
    Time: "9:00 am-9:00pm",
    TotalConsultation: "3920",
    Ratingscount: "800+",
    Ratings: "4 Star Reviews",
    Fee: "1500",
    uri: "https://picsum.photos/200/300/?blur",
  },
  {
    id: "5",
    Name: "Dr. Martin Thapar",
    Category: "Neurologist",
    Hospital: "City Hospital",
    Time: "2:00 pm-8:00pm",
    TotalConsultation: "2987",
    Ratingscount: "500+",
    Ratings: "4 Star Reviews",
    Fee: "1900",
    uri: "https://picsum.photos/id/870/200/300?grayscale&blur=2",
  },
  {
    id: "6",
    Name: "Dr. Jainti Deendayal",
    Category: "MD Physician",
    Hospital: "CareForYou Hospital",
    Time: "12:00 am-8:00am",
    TotalConsultation: "7980",
    Ratingscount: "200+",
    Ratings: "5 Star Reviews",
    Fee: "5000",
    uri: "https://picsum.photos/id/237/200/300",
  },
  {
    id: "7",
    Name: "Dr. Vibhuti Mishra",
    Category: "ENT Specialist",
    Hospital: "Trimurti Hospital",
    Time: "2:00 am-12:00pm",
    TotalConsultation: "3981",
    Ratingscount: "500+",
    Ratings: "4 Star Reviews",
    Fee: "2200",
    uri: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: "8",
    Name: "Dr. Manmohan Tiwari",
    Category: "MD",
    Hospital: "Bhadarka Hospital",
    Time: "2:00 pm-8:00pm",
    TotalConsultation: "980",
    Ratingscount: "200+",
    Ratings: "4 Star Reviews",
    Fee: "900",
    uri: "https://picsum.photos/200/300?grayscale",
  },
  {
    id: "9",
    Name: "Dr. Vaneet Kapur",
    Category: "Neurologist",
    Hospital: "Sparsh Hospital",
    Time: "8:00 am-8:00pm",
    TotalConsultation: "783",
    Ratingscount: "150+",
    Ratings: "4 Star Reviews",
    Fee: "700",
    uri: "https://picsum.photos/200/300/?blur",
  },
  {
    id: "10",
    Name: "Dr. Vikas Khanna",
    Category: "Cardiologist",
    Hospital: "Zydus Hospital",
    Time: "10:00 am-8:00pm",
    TotalConsultation: "180",
    Ratingscount: "70+",
    Ratings: "4 Star Reviews",
    Fee: "650",
    path: "https://picsum.photos/id/870/200/300?grayscale&blur=2",
  },
];

module.exports = flatlistdata;
